require('dotenv').config();
accoundSID=process.env.accoundSID
authToken=process.env.authToken
module.exports={
USER_COLLECTION:'user',
ADMIN_COLLECTION:'admin',
PRODUCT_COLLECTION:'product',
RESTAURANT_COLLECTION:'restaurant',
COUPON_COLLECTION:'Coupons',
CUSINE_COLLECTION:'cusine',
SUPER_NOTIFICATIONS:'notification',
CART_COLLECTION:'cart',
ORDER_COLLECTION:'order',
BANNER_COLLECTION:'banner',
ADDRESS_COLLECTION:'address',
WALLET_COLLECTION:'wallet',
ServiceId:'VA978ba94f2f7b557539a57f91ecb2f2b8', 
accoundSID:accoundSID,
authToken:authToken
}